### ISSUE TITLE
Cannot fit videos larger than 100mb into repo

### ISSUE THREAD

**Issue by caseyyee** [MozVR/webvr-demos#1]
May need to find a way to pull down the binaries from a location rather than trying to stuff them into github.    100mb gives you some pretty crappy video quality for webvr.

**Comment by bluemarvin** [comment]
Have you looked into this: https://git-lfs.github.com ?

**Comment by caseyyee** [comment]
Huh.  I'll look into this.   Thanks!

**Comment by caseyyee** [comment]
Ah, I also noticed that @cvan has a post-install that rips it off the site:
https://github.com/MozVR/webvr-demos/blob/master/package.json#L27

**Comment by caseyyee** [comment]
Im also noticing that syncmedia will re-download the file even if its already there.   A simple check would help avoid the transfer.

**Comment by caseyyee** [comment]
Solution in place seems serviceable.

**Comment by cvan** [comment]
> Im also noticing that syncmedia will re-download the file even if its already there. A simple check would help avoid the transfer.

yeah, I included the video download process in `postinstall`, so it gets called every time you run `npm install` (or manually call `npm run postinstall`). (git-lfs is cool.) I was going to do a [bash `if` statement](http://www.cyberciti.biz/faq/unix-linux-test-existence-of-file-in-bash/) to check for the file but didn't, since it was getting a bit hairy in that npm script heh :haircut:. 

I just opened PR #6 - let me know!
